# =============================================================================
# Team Credentials Module
# =============================================================================
# This module handles saving SSH keys to files and generating credentials
# documentation, separate from key generation and infrastructure provisioning.
# =============================================================================

# =============================================================================
# Team Directory Structure
# =============================================================================

resource "local_file" "team_dir_marker" {
  for_each = var.teams

  filename = "${path.module}/${var.secrets_path}/team-${each.key}/.gitkeep"
  content  = ""
}

# =============================================================================
# Keys
# =============================================================================

resource "local_file" "team_private_key" {
  for_each = var.teams

  filename        = "${path.module}/${var.secrets_path}/team-${each.key}/${each.value.user}-key"
  content         = var.team_private_keys[each.key]
  file_permission = "0600"
}

resource "local_file" "team_public_key" {
  for_each = var.teams

  filename = "${path.module}/${var.secrets_path}/team-${each.key}/${each.value.user}-key.pub"
  content  = var.team_public_keys[each.key]
}

# =============================================================================
# SSH Config Files
# =============================================================================

# Track team IP changes with terraform_data for controlled updates
resource "terraform_data" "team_ip_tracker" {
  for_each = var.teams

  input = {
    team_id    = each.key
    user       = each.value.user
    private_ip = each.value.private_ip
  }
}

resource "local_file" "team_ssh_config" {
  for_each = var.teams

  filename = "${path.module}/${var.secrets_path}/team-${each.key}/ssh-config"
  content = templatefile("${path.module}/../../templates/team/ssh-config.tpl", {
    team_user       = each.value.user
    domain          = var.domain
    jump_user       = var.jump_user
    team_private_ip = terraform_data.team_ip_tracker[each.key].output.private_ip
  })

  depends_on = [terraform_data.team_ip_tracker]
}

# =============================================================================
# Participant Setup Scripts
# =============================================================================

resource "local_file" "team_setup_sh" {
  for_each = var.teams

  filename        = "${path.module}/${var.secrets_path}/team-${each.key}/setup.sh"
  content = templatefile("${path.module}/../../templates/team/setup.sh.tpl", {
    team_user = each.value.user
  })
  file_permission = "0755"
}

resource "local_file" "team_setup_ps1" {
  for_each = var.teams

  filename = "${path.module}/${var.secrets_path}/team-${each.key}/setup.ps1"
  content = templatefile("${path.module}/../../templates/team/setup.ps1.tpl", {
    team_user = each.value.user
  })
}

resource "local_file" "team_readme" {
  for_each = var.teams

  filename = "${path.module}/${var.secrets_path}/team-${each.key}/README.md"
  content = templatefile("${path.module}/../../templates/team/README.md.tpl", {
    team_user = each.value.user
    domain    = var.domain
  })
}

# =============================================================================
# Teams Credentials Summary JSON
# =============================================================================

resource "local_file" "teams_credentials_json" {
  filename = "${path.module}/${var.secrets_path}/teams-credentials.json"
  content = jsonencode({
    bastion = {
      host   = var.bastion_ip
      user   = var.jump_user
      domain = "bastion.${var.domain}"
    }
    teams = {
      for team_id, team_config in var.teams :
      team_id => {
        user        = team_config.user
        private_ip  = team_config.private_ip
        domain      = "${team_config.user}.${var.domain}"
        ssh_command = "ssh -F ~/.ssh/ai-south-hack/ssh-config ${team_config.user}"
        folder      = "secrets/team-${team_id}/"
        files = {
          key       = "${team_config.user}-key"
          ssh_config = "ssh-config"
          setup_sh  = "setup.sh"
          setup_ps1 = "setup.ps1"
          readme    = "README.md"
        }
      }
    }
    traefik = {
      auto_config   = "secrets/traefik-dynamic-auto.yml"
      custom_config = "secrets/traefik-dynamic-custom.yml"
      note          = "auto_config is regenerated by Terraform, custom_config is for manual additions"
    }
  })
}
